apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mastodon
  namespace: mastodon
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - secretName: mastodon
    hosts:
    - gayhorse.club
  rules:
  - host: gayhorse.club
    http:
      paths:
      - path: /api/v1/streaming
        backend:
          serviceName: streaming-ingress
          servicePort: 4000
      - path: /
        backend:
          serviceName: web-ingress
          servicePort: 3000
